In [2]:
import numpy as np

In [10]:
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
B=np.linspace(14,16,8).reshape(2,4)
print(B)

[[14.         14.28571429 14.57142857 14.85714286]
 [15.14285714 15.42857143 15.71428571 16.        ]]


In [12]:
C=np.array([4,3,2,4,2,6,7,3]).reshape(2,2,2)#Changes neesds saving in another variable
print(C)

[[[4 3]
  [2 4]]

 [[2 6]
  [7 3]]]


In [14]:
D=np.array([4,3,2,4,2,6,7,3])
D.resize(2,2,2)#Changes the shape of original array
print(D)

[[[4 3]
  [2 4]]

 [[2 6]
  [7 3]]]


In [15]:
#Numpy arrays operations
a=np.array([5,23,13,3,8])
b=np.array([4,21,3,4,3])
c=a-b
print(c)

[ 1  2 10 -1  5]


In [16]:
a=np.array([5,23,13,3,8])
b=np.array([4,21,3,4,3])
c=a+b
print(c)

[ 9 44 16  7 11]


In [20]:
#Matrix multiplication
a=np.array([5,23,13,3,8,9]).reshape(2,3)
b=np.array([4,21,3,4,3,6]).reshape(3,2)
print(a)
print(b)
c=a@b
print(c)

[[ 5 23 13]
 [ 3  8  9]]
[[ 4 21]
 [ 3  4]
 [ 3  6]]
[[128 275]
 [ 63 149]]


In [21]:
#Matrix multiplication
a=np.array([5,23,13,3,8,9]).reshape(2,3)
b=np.array([4,21,3,4,3,6]).reshape(3,2)
print(a)
print(b)
c=a.dot(b)
print(c)

[[ 5 23 13]
 [ 3  8  9]]
[[ 4 21]
 [ 3  4]
 [ 3  6]]
[[128 275]
 [ 63 149]]


In [22]:
#max & min works only for numeric data types like integer and float
q=np.array([21,74,8,34,20])
print(q.max())
print(q.min())

74
8


In [24]:
q=np.array([21,74,8,34]).reshape(2,2)
print(q)
print(q.max(axis=0))#column wise bigger number
print(q.max(axis=1))#row wise bigger number

[[21 74]
 [ 8 34]]
[21 74]
[74 34]


In [25]:
q=np.array([21,74,8,34]).reshape(2,2)
print(q)
print(q.min(axis=0))#column wise smaller number
print(q.min(axis=1))#row wise smaller number

[[21 74]
 [ 8 34]]
[ 8 34]
[21  8]


In [27]:
#Joining arrays vertically
a=np.array([5,23,13,3]).reshape(2,2)
b=np.array([4,21,3,4]).reshape(2,2)
print(a)
print(b)
print(np.vstack((a,b)))

[[ 5 23]
 [13  3]]
[[ 4 21]
 [ 3  4]]
[[ 5 23]
 [13  3]
 [ 4 21]
 [ 3  4]]


In [28]:
#Joining arrays Horizontally
a=np.array([5,23,13,3]).reshape(2,2)
b=np.array([4,21,3,4]).reshape(2,2)
print(a)
print(b)
print(np.hstack((a,b)))

[[ 5 23]
 [13  3]]
[[ 4 21]
 [ 3  4]]
[[ 5 23  4 21]
 [13  3  3  4]]


In [29]:
a=np.array([5,23,13,3]).reshape(2,2)
b=np.array([4,21,3,4]).reshape(2,2)
print(a)
print(b)
print(np.stack((a,b),axis=0))

[[ 5 23]
 [13  3]]
[[ 4 21]
 [ 3  4]]
[[[ 5 23]
  [13  3]]

 [[ 4 21]
  [ 3  4]]]


In [30]:
a=np.array([5,23,13,3]).reshape(2,2)
b=np.array([4,21,3,4]).reshape(2,2)
print(a)
print(b)
print(np.stack((a,b),axis=1))
#no.of rows will be no.of groups
#no. of columns in every group will be no. of every group


[[ 5 23]
 [13  3]]
[[ 4 21]
 [ 3  4]]
[[[ 5 23]
  [ 4 21]]

 [[13  3]
  [ 3  4]]]


In [31]:
A=np.arange(30).reshape(2,3,5)
print(A)
print(np.dstack(A))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [32]:
#Splitting arrays
A=np.arange(18).reshape(6,3)
print(A)
print(np.vsplit(A,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


In [35]:
A=np.arange(18).reshape(6,3)
print(A)
print(np.vsplit(A,(2,3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]


In [36]:
A=np.arange(18).reshape(6,3)
print(A)
print(np.vsplit(A,(2,5)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]), array([[15, 16, 17]])]


In [39]:
A=np.arange(18).reshape(3,6)
print(A)
print(np.hsplit(A,(2,5)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16]]), array([[ 5],
       [11],
       [17]])]


In [40]:
a=np.array([5,23,13,3]).reshape(2,2)
print(a)
print(a.argmax())

[[ 5 23]
 [13  3]]
1


In [41]:
a=np.array([5,23,13,3]).reshape(2,2)
print(a)
print(a.argmax(axis=0))

[[ 5 23]
 [13  3]]
[1 0]


In [42]:
a=np.array([5,23,13,3]).reshape(2,2)
print(a)
print(a.argmax(axis=1))

[[ 5 23]
 [13  3]]
[1 0]


In [43]:
a=np.array([5,23,13,3]).reshape(2,2)
print(a)
print(a.argmin())

[[ 5 23]
 [13  3]]
3


STATISTICS

In [48]:
#Mean,Median,std,variance
A=np.array([24,3,56,42,12])
print("Mean:",np.mean(A))
print("Median:",np.median(A))
print("Variance:",np.var(A))
print("Standard Deviation",np.std(A))

Mean: 27.4
Median: 24.0
Variance: 375.03999999999996
Standard Deviation 19.365949499056327


TRIGNOMETRY

In [47]:
#PI VALUE
a=np.pi
print(a)#radians
print(np.rad2deg(a))#converts radians to degree

3.141592653589793
180.0


In [49]:
#Radians to degree conversion
A=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(np.rad2deg(A))

[ 45.  60.  90. 180.]


In [52]:
#Degree to radians conversion
r=np.array([0,30,45,60,90,120,180])
c=np.deg2rad(r)
print(c)


[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [53]:
np.sin(r)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [54]:
np.cos(r)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [55]:
np.tan(r)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [56]:
np.arcsin(0)#sin^-1

0.0

In [58]:
np.arccos(1)#cos^-1

0.0

In [59]:
np.arctan(1)#tan^-1

0.7853981633974483

In [60]:
a=9
b=7
print(np.hypot(a,b))

11.40175425099138


SEARCHING

In [61]:
A=np.array([32,2,4,5,21,8])
print(np.where(A==8))

(array([5]),)


In [62]:
A=np.array([32,2,4,5,21,8])
print(np.where(A>8))

(array([0, 4]),)


In [4]:
A=np.array([32,2,4,5,21,8])
print(np.searchsorted(A,8))

4


Linear algebra and func

In [8]:
A=np.array([5,8,74,14])
B=np.array([50,7,88,1])
print("Sum :",np.add(A,B))
print("Difference:",np.subtract(A,B))
print("Product",np.multiply(A,B))
print("Quotient",np.divide(A,B))
print("Remainder",np.mod(A,B))
print(np.divmod(A,B))

Sum : [ 55  15 162  15]
Difference: [-45   1 -14  13]
Product [ 250   56 6512   14]
Quotient [ 0.1         1.14285714  0.84090909 14.        ]
Remainder [ 5  1 74  0]
(array([ 0,  1,  0, 14]), array([ 5,  1, 74,  0]))


SORT

In [11]:
A=np.array([5,8,74,14])
print(np.sort(A))

[ 5  8 14 74]


SET FUNCTIONS

In [15]:
A=np.array([5,7,74,14])
B=np.array([50,7,88,1])
print(np.union1d(A,B))

[ 1  5  7 14 50 74 88]


In [16]:
A=np.array([5,7,74,14])
B=np.array([50,7,88,1])
print(np.setdiff1d(A,B))


[ 5 14 74]


In [17]:
A=np.array([5,7,74,14])
B=np.array([50,7,88,1])
print(np.intersect1d(A,B))

[7]


ROUNDING

In [20]:
a=np.trunc([2.0983,-6.9182])
print(a)

[ 2. -6.]


In [21]:
a=np.fix([2.0983,-6.9182])
print(a)

[ 2. -6.]


In [23]:
a=np.around(2.0983,2)
print(a)

2.1


In [24]:
a=np.floor([2.0983,-6.9182])
print(a)

[ 2. -7.]


In [25]:
a=np.ceil([2.0983,-6.9182])
print(a)

[ 3. -6.]


More Functions

In [27]:
#Cumulative Sum
a=np.array([9,3,4,12,5,3])
print(np.cumsum(a))

[ 9 12 16 28 33 36]


In [28]:
#Cumulative Product
a=np.array([9,3,4,12,5,3])
print(np.cumprod(a))


[    9    27   108  1296  6480 19440]


In [32]:
#LCM & GCD
print("LCM:",np.lcm(43,76))
print("GCD:",np.gcd(222,86))

LCM: 3268
GCD: 2


In [31]:
#LCM & GCD for multiple elements
a=np.array([9,3,4,12,5,3])
print("LCM:",np.lcm.reduce(a))
print("GCD:",np.gcd.reduce(a))


LCM: 180
GCD: 1


In [34]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [35]:
from numpy import random as rd

In [36]:
a=rd.rand()#limit-0 to 0.99
print(a)

0.5175978205336816


In [41]:
a=rd.randint(4)#limit - 0 to 4
print(a)

2


In [42]:
a=rd.randint(40,size=6)#limit with size
print(a)

[ 7  2 17 37 30 21]


In [43]:
a=rd.randint(40,size=(3,3))#limit with shape
print(a)

[[32 38 11]
 [ 0 11  2]
 [25 31 15]]


In [44]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.inner(a,b))

32


In [45]:
#[1*4 1*5 1*6]
#[2*4 2*5 2*6]....
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.outer(a,b))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [46]:
#Cross joint / Determinant
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.cross(a,b))

[-3  6 -3]
