In [ ]:
# variable & string
a=18
print("Iam ",a,"years old");

Iam  18 years old


In [ ]:
#Arithmetic  of two integer variables
a=int(input("Enter a number"))
b=int(input("Enter other number"))
print("Sum is",a+b)
print("Difference is",a-b)
print("Product is",a*b)
print("Quotient is",a/b)
print("Remainder is",a%b)
print("Power of a to b",a**b)
print("Floor division",a//b)

Enter a number25
Enter other number12
Sum is 37
Difference is 13
Product is 300
Quotient is 2.0833333333333335
Remainder is 1
Power of a to b 59604644775390625
Floor division 2


In [ ]:
#Take salary from the user.If the salary is more than 50k there is a 10% tax.Print his final salary.
s=int(input("Enter salary"))
if(s>=50000):
  print("Your final salary is",s-((0.1)*s))
else:
  print("There is no tax deduction")


Enter salary7000000
Your final salary is 6300000.0


In [ ]:
#Get the salary  from the user if the salary is >= 50k apply 10% tax deduction .if the salary is < 50k apply 5% tax,if the salary > 70kapply 12% tax if salary exceeds 1L print you are promoted
s=int(input("Enter salary"))
if(s<50000):
  print("Your final salary is",s-((0.05)*s))
elif(s<=70000):
  print("Your final salary is",s-((0.1)*s))
elif(s<=100000):
  print("Your final salary is",s-((0.12)*s))
else:
  print("You are promoted")


Enter salary120000
You are promoted


In [ ]:
#for loop:
n=int(input("Enter n value: "))
r=range(1,11)
for i in r:
  print(n ,"X", i , "=", n*i)

Enter n value: 141
141 X 1 = 141
141 X 2 = 282
141 X 3 = 423
141 X 4 = 564
141 X 5 = 705
141 X 6 = 846
141 X 7 = 987
141 X 8 = 1128
141 X 9 = 1269
141 X 10 = 1410


In [ ]:
n=int(input("Enter n value"))
i=1
while(i<11):
  print(n ,"X", i , "=", n*i)
  i=i+1

Enter n value14
14 X 1 = 14
14 X 2 = 28
14 X 3 = 42
14 X 4 = 56
14 X 5 = 70
14 X 6 = 84
14 X 7 = 98
14 X 8 = 112
14 X 9 = 126
14 X 10 = 140


In [ ]:
#list:Heterogeneous
l=[1,'g','@',6]
print(l[::-1])

[6, '@', 'g', 1]


In [ ]:
#Mutable:
l.append("append")#adds element at last of the list
l.insert(3,'Hi')#listname.insert(index,element)
print(l)

[1, 'g', '@', 'Hi', 6, 'append']


In [ ]:
l1=[2,'python']
l.extend(l1) #l=l+l1
#list1.extend(list2)
print(l)


[1, 'g', '@', 6, 2, 'python']


In [ ]:
l.pop()#list.pop(index)
#deletes the last element
l.remove(1)#list.remove(element)
#deletes the given element
print(l)

['g', '@', 6, 2]


In [ ]:
l.clear()
print(l)

[]


In [ ]:
#Create a list 10 random integer elements and print their squares and save them in a new list
l=[2,7,4,5,3,13,76,81,6]
l2=[]
for i in l:
  l2.append(i*i)
print(l2)

[4, 49, 16, 25, 9, 169, 5776, 6561, 36]


In [ ]:
#List Comprehension
#newlist=[output for if cond]
res=[i*i for i in l if i>50]
print(res)

[5776, 6561]


In [ ]:
#newlist=[(stof if) if(cond) else (st of else) for]
l=[2,7,4,5,3,13,76,81,6]
res=[i*i if i>50 else 'X' for i in l]
print(res)

['X', 'X', 'X', 'X', 'X', 'X', 5776, 6561, 'X']


In [ ]:
#Take the salary from the user if it salary < 50k 10% tax otherwise 15% tax
s=[50000,90000,8700,75000]
l3=[i-(0.1*i) if i<50000 else i-(0.15*i) for i in s]
print(l3)

[42500.0, 76500.0, 7830.0, 63750.0]


In [ ]:
#creating a dictionary
dict1={"mentor":'Jwalitha',2:'likhita',4:'ramya',5:'Lavanya'}
print(dict1[5])


Lavanya


In [ ]:
#To print required details
dict2={"Dept":'CSE','details':{'year':2,'Sec':'D',"Strength":71}}
print("Year is ",dict2["details"]["year"])
print("Section is",dict2["details"]["Sec"])
print("Count is ",dict2["details"]["Strength"])

Year is  2
Section is D
Count is  71


In [ ]:
i=[1,2,3,4]
j=['a','b','c','d']
new_zip=(zip(i,j))
for i in new_zip:
  print(i)


(1, 'a')
(2, 'b')
(3, 'c')
(4, 'd')


In [ ]:
i=[1,2,3,4]
j=['a','b','c','d']
new_dict=(zip(i,j))
print(dict(new_dict))

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}


In [ ]:
#numpy
import numpy as np
a=np.array([1,2,3,4])#1d array
print(a.ndim)
print(a.shape)


1
(4,)


In [ ]:
#Create a 2 dimensional array
b=np.array([[1,2,3,4],['a','b','c','d'],['@','#','!','$']])
print(b)
print(b.ndim)
print(b.shape)

[['1' '2' '3' '4']
 ['a' 'b' 'c' 'd']
 ['@' '#' '!' '$']]
2
(3, 4)


In [ ]:
#Create a 3 dimensional array
c=np.array([[[1,2,3],[4,5,6]],[['a','b','c'],['d','e','f']]])
print(c)
print(c.ndim)
print(c.shape)

[[['1' '2' '3']
  ['4' '5' '6']]

 [['a' 'b' 'c']
  ['d' 'e' 'f']]]
3
(2, 2, 3)


In [ ]:
z=np.ones((2,3,4))#(g,r,c)
print(z)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
z=np.zeros((2,3,4))#(g,r,c)
print(z)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
#Identity Matrix
y=np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
w=np.arange(1,11)
print(w)
print(type(w))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [ ]:
#Print all the numbers that are divisible by 8 using arange b/w 1 to 1000
e=np.arange(8,1000,8)
print(e)

[  8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136 144
 152 160 168 176 184 192 200 208 216 224 232 240 248 256 264 272 280 288
 296 304 312 320 328 336 344 352 360 368 376 384 392 400 408 416 424 432
 440 448 456 464 472 480 488 496 504 512 520 528 536 544 552 560 568 576
 584 592 600 608 616 624 632 640 648 656 664 672 680 688 696 704 712 720
 728 736 744 752 760 768 776 784 792 800 808 816 824 832 840 848 856 864
 872 880 888 896 904 912 920 928 936 944 952 960 968 976 984 992]


In [ ]:
#Spliting a range of numbers having common difference
q=np.linspace(3,2,12)
print(q)

[3.         2.90909091 2.81818182 2.72727273 2.63636364 2.54545455
 2.45454545 2.36363636 2.27272727 2.18181818 2.09090909 2.        ]


In [ ]:
#creating a tuple
t=(1,2,3,4)
print(t)

(1, 2, 3, 4)


In [ ]:
T="python"
print(tuple(T))

('p', 'y', 't', 'h', 'o', 'n')


In [ ]:
print(T[0])

p


In [ ]:
print(T[-1])

n


In [ ]:
print(T[0:4])

pyth


In [ ]:
print('p' in T)

True


In [ ]:
print('r' in T)

False


In [ ]:
s={1,2,3,4}
s1={4,7,5,3}
print(s)

{1, 2, 3, 4}


In [ ]:
x=s.union(s1)
print(x)

{1, 2, 3, 4, 5, 7}


In [ ]:
print(s.intersection(s1))

{3, 4}


In [ ]:
print(s.difference(s1))

{1, 2}


In [ ]:
print(s.clear())

None


In [ ]:
a=[9,5,34,2,1]
a.sort()
print(a)

[1, 2, 5, 9, 34]


In [1]:
a=(9,5,34,2,1)
b=sorted(a)
print(a)
print(b)

(9, 5, 34, 2, 1)
[1, 2, 5, 9, 34]
